# -*- coding: utf-8 -*-
"""Pandas / Polars

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16a1C6THghaAP96nu8NRwpHVikH_Y7F9X

# Что такое Polars и почему он быстрее Pandas?
Polars — это библиотека для работы с датафреймами, предназначенная для распараллеливания. Она создана с нуля и написана на языке Rust, но также имеет пакет для Python, что делает ее потенциальной альтернативой Pandas.

В Polars есть два разных API: нетерпеливый и ленивый. Нетерпеливый API похож на Pandas, а ленивый более эффективен, поскольку позволяет избежать выполнения ненужного кода.

Polars быстрее Pandas, поскольку использует все доступные ядра вашего компьютера. Синтаксис Polars отличается от синтаксиса Pandas, и он позволяет выполнять операции параллельно. Однако код на Polars обычно немного длиннее, чем на Pandas. Если вам нужно обработать большой объем данных, Polars может стать хорошей альтернативой Pandas.

# Бенчмарк операций, подобных тем, что выполняются в базах данных

#Сравнение Pandas и Polars
На первый взгляд, синтаксис Pandas и Polars (нетерпеливый API) похож из-за общих основных структурных элементов: Series и DataFrames.

В этом разделе рассматриваются основные отличия пакета Polars от Pandas в плане синтаксиса и времени выполнения:

- Чтение данных
- Выбор и фильтрация данных
- Создание новых столбцов
- Группировка и агрегирование
- Работа с отсутствующими данными
"""

!pip install polars --q

"""##Чтение данных
Чтение CSV-файла в Polars покажется вам знакомым, потому что вы можете использовать метод .read_csv(), как в Pandas:
"""

# Commented out IPython magic to ensure Python compatibility.
# %%time
# import pandas as pd
# 
# # Pandas
# df_pd = pd.read_csv("https://raw.githubusercontent.com/RandomFractals/chicago-crimes/main/data/crimes-2022.csv")

# Commented out IPython magic to ensure Python compatibility.
# %%time
# import polars as pl
# 
# # Polars
# df_pl = pl.read_csv("https://raw.githubusercontent.com/RandomFractals/chicago-crimes/main/data/crimes-2022.csv")

"""##Выбор и фильтрация данных
Первое существенное различие между Pandas и Polars заключается в том, что в Polars не используется индекс.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%time
# # Pandas
# df_pd[['ID', 'Case Number', 'Date']]

# Commented out IPython magic to ensure Python compatibility.
# %%time
# # Приведенный выше код будет работать и в Polars,
# # но в Polars это делается правильно так:
# df_pl.select(pl.col(['ID', 'Case Number', 'Date']))

# Commented out IPython magic to ensure Python compatibility.
# %%time
# # Pandas
# df_pd.query('Year > 2021')

# Commented out IPython magic to ensure Python compatibility.
# %%time
# # Polars
# df_pl.filter(pl.col('Year') > 2021)

"""##Создание новых столбцов
Создание нового столбца в Polars также отличается от того, к чему вы привыкли в Pandas. В Polars нужно использовать метод .with_column() или .with_columns() в зависимости от того, сколько столбцов вы хотите создать.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%time
# # Pandas
# df_pd["new_year"] = df_pd["Year"]

# Commented out IPython magic to ensure Python compatibility.
# %%time
# # Polars
# df_pl.with_columns([(pl.col("Year")).alias("new_year")])
#

# Commented out IPython magic to ensure Python compatibility.
# %%time
# # Polars для нескольких столбцов
# # df.with_columns([(pl.col("col") * 10).alias("new_col"), ...])

"""##Группировка и агрегирование
Группировка и агрегирование в Pandas и Polars немного отличаются синтаксисом, но в обоих случаях используются методы .groupby() и .agg().
"""

# Commented out IPython magic to ensure Python compatibility.
# %%time
# # Pandas
# df_pd.groupby('Year')['Arrest'].agg('value_counts')

# Commented out IPython magic to ensure Python compatibility.
# %%time
# # Polars
# # df.groupby('col1').agg([pl.col('col2').mean()]) # As suggested in Polars docs
# df_pl.groupby('Year').agg([pl.col(['Arrest']).value_counts()]) # Shorter

"""##Пропущенные данные
Еще одно существенное различие между Pandas и Polars заключается в том, что Pandas использует значения NaN для обозначения пропущенных значений, а Polars — null.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%time
# # Pandas
# df_pd['Location'].fillna(-999)

# Commented out IPython magic to ensure Python compatibility.
# %%time
# # Polars
# # df_pl.with_column(pl.col('col2').fill_null(pl.lit(-999))) # As suggested in Polars docs
# df_pl.with_column(pl.col('Location').fill_null(-999)) # Shorter

import pandas as pd

# Создадим датафрейм из 1000 строк
df = pd.DataFrame({'col1': range(1000), 'col2': ['abc'] * 1000})

# Получим общий размер DataFrame в памяти (в байтах)
total_size = df.memory_usage(deep=True).sum()

# Вычислим среднее потребление памяти на строку (в байтах)
row_size = total_size / len(df)

# Вычислим использование памяти для 1 миллиона строк (в байтах)
million_rows_size = row_size * 1000000

print(f"Среднее использование памяти на строку: {row_size:.2f} bytes")
print(f"Использование памяти для 1 миллиона строк: {million_rows_size:.2f} bytes")

