# -*- coding: utf-8 -*-
"""Лабораторная 1. Работа с Polars.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ODZKk627wUBRfRHlMSC1lAIB1gYSJ9Bl

# Лабораторная работа 1. Работа с Polars (или Pandas*)

Скачать данные по ссылке: https://docs.google.com/spreadsheets/d/1bqhgCMkZyRzZAT7WO1SqCXc05ihQIRz-/edit?usp=sharing&ouid=107115649530671458477&rtpof=true&sd=true

Создать выходной файл вида: https://docs.google.com/spreadsheets/d/153QNK7OIXP2vh5a57iVkNhY0Y4R3qBy0/edit?gid=1362714490#gid=1362714490

### Создать таблицу в Polars со стоблцами: Заголовок (T1), Автор (AU), Год (PY), Ключевые слова (KW), DOI (DO), аннотация (AB) по заданному файлу

Примечание 1: авторов и ключевые слова нужно записывать в ячейку для каждой статьи в виде списка; число строк, занимаемое каждым журналом, можно подсчитать с помощью пропущенных значений
"""

# pip install polars
# pip install fastexcel
# pip install xlsxwriter

""" Примечание 2*: При выполнении работы с помощью Pandas max = 8 баллов"""

# data = pd.read_excel('E:\\...\\Merged file.xlsx', index_col=0) # считать файл в Excel

# data.drop(['VL'], axis= 1 , inplace= True) # удалить лишние колонки

# data.head(10) # печатаем первые 10 строк

# df = df.drop(index=[100, 201]) # удаляем лишние строки
# df = df.reset_index(drop=True) # переписываем индексы

# df = pd.DataFrame(data={'Title': title_res, 'Author': res_author,  'Year': year_res, 'Key Words': res_keyWords, 'DOI': doi_res, 'Abstract': abstract_res})

# df.to_excel("E:\\...\\exit.xlsx", sheet_name='Sheet_name_1')